name: QuickHarvest
main: io.github.rypofalem.quickharvest.QuickHarvestPlugin
version: 1.0
api-version: 1.13
website: rypofalem.github.io
author: RypoFalem
description: Right click fully grown crops to harvest and replant at once.
depend: [GenericEvents]
softdepend: [Custom]
permissions:
  quickharvest.use:
    description: Can use quick harvest
    default: true